FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt .
RUN pip install --user -r requirements.txt

COPY src/app.py ${LAMBDA_TASK_ROOT}

# Command can be overwritten by providing a different command in the template directly.
CMD ["app.lambda_handler"]