name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt -t ./deps
      - name: Zipping output code
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r deps.zip deps
      - name: copy deps and source file into output folder
        run: |
          mkdir output
          cp deps.zip output/
          cp lambda_function.py output/
      - name: Zipping output code
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r output.zip output
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: test-lambda
          zip_file: output.zip
          dry_run: true